google.client.id=462941574651-08lfhtvomnhq4qhotkei01r5eu6uougj.apps.googleusercontent.com
google.client.secret=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
google.redirect.uri=http://localhost:8080/AuraSound_war/login